name = "worker"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = false

routes = [

  { pattern = "afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud1.dpdns.org", custom_domain = true },
]

[observability.logs]
enabled = true


