name = "worker"
main = "_worker.js"
compatibility_date = "2023-05-26"
workers_dev = false

routes = [

  { pattern = "afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud1.dpdns.org", custom_domain = true },
  { pattern = "afrcloud2.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud2.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud2.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud2.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud2.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud2.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud2.dpdns.org", custom_domain = true },
  { pattern = "afrcloud3.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud3.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud3.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud3.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud3.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud3.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud3.dpdns.org", custom_domain = true },
  { pattern = "afrcloud4.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud4.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud4.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud4.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud4.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud4.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud4.dpdns.org", custom_domain = true },
  { pattern = "afrcloud5.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud5.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud5.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud5.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud5.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud5.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud5.dpdns.org", custom_domain = true },
  { pattern = "afrcloud6.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud6.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud6.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud6.dpdns.org", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud6.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud6.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud6.dpdns.org", custom_domain = true },
]

[observability.logs]
enabled = true


